import geopandas as gpd
import matplotlib.pyplot as plt

map_names = {
    'Cyprus': 'N. Cyprus',
    'Russian federation': 'Russia',
    'Sudan': 'S. Sudan',
    'Korea, republic of': 'South Korea',
    'Tanzania, United Republic of': 'Tanzania',
    'Bolivia, Plurinational State of': 'Bolivia',
    'Viet Nam': 'Vietnam',
    'Bosnia and herzegovina': 'Bosnia and Herz.',
    'Brunei Darussalam': 'Brunei',
    'Central African Republic': 'Central African Rep.',
    'Czech republic': 'Czechia',
    'Congo, Democratic Republic of the': 'Dem. Rep. Congo',
    'Dominican Republic': 'Dominican Rep.',
    'Equatorial Guinea': 'Eq. Guinea',
    'Iran, Islamic Republic of': 'Iran',
    'Lao People\'s Democratic Republic': 'Laos',
    'Libya, state of': 'Libya',
    'Macedonia, north': 'Macedonia',
    'Moldova, republic of': 'Moldova',
    'Afghanistan': 'Afghanistan',
    'Albania': 'Albania',
    'Algeria': 'Algeria',
    'Angola': 'Angola',
    'Argentina': 'Argentina',
    'Armenia': 'Armenia',
    'Australia': 'Australia',
    'Austria': 'Austria',
    'Azerbaijan': 'Azerbaijan',
    'Bahamas': 'Bahamas',
    'Bangladesh': 'Bangladesh',
    'Belarus': 'Belarus',
    'Belgium': 'Belgium',
    'Belize': 'Belize',
    'Benin': 'Benin',
    'Botswana': 'Botswana',
    'Brazil': 'Brazil',
    'Bulgaria': 'Bulgaria',
    'Burkina Faso': 'Burkina Faso',
    'Burundi': 'Burundi',
    'Cambodia': 'Cambodia',
    'Cameroon': 'Cameroon',
    'Canada': 'Canada',
    'Chad': 'Chad',
    'Chile': 'Chile',
    'China': 'China',
    'Colombia': 'Colombia',
    'Congo': 'Congo',
    'Costa Rica': 'Costa Rica',
    'Croatia': 'Croatia',
    'Cuba': 'Cuba',
    'Cyprus': 'Cyprus',
    "Côte d'Ivoire": "Côte d'Ivoire",
    'Denmark': 'Denmark',
    'Djibouti': 'Djibouti',
    'Ecuador': 'Ecuador',
    'Egypt': 'Egypt',
    'El Salvador': 'El Salvador',
    'Estonia': 'Estonia',
    'Eswatini': 'eSwatini',
    'Ethiopia': 'Ethiopia',
    'Fiji': 'Fiji',
    'Finland': 'Finland',
    'France': 'France',
    'Gabon': 'Gabon',
    'Gambia': 'Gambia',
    'Georgia': 'Georgia',
    'Germany': 'Germany',
    'Ghana': 'Ghana',
    'Greece': 'Greece',
    'Guatemala': 'Guatemala',
    'Guinea': 'Guinea',
    'Guinea-Bissau': 'Guinea-Bissau',
    'Guyana': 'Guyana',
    'Haiti': 'Haiti',
    'Honduras': 'Honduras',
    'Hungary': 'Hungary',
    'Iceland': 'Iceland',
    'India': 'India',
    'Indonesia': 'Indonesia',
    'Iraq': 'Iraq',
    'Ireland': 'Ireland',
    'Israel': 'Israel',
    'Italy': 'Italy',
    'Jamaica': 'Jamaica',
    'Japan': 'Japan',
    'Jordan': 'Jordan',
    'Kazakhstan': 'Kazakhstan',
    'Kenya': 'Kenya',
    'Kuwait': 'Kuwait',
    'Kyrgyzstan': 'Kyrgyzstan',
    'Latvia': 'Latvia',
    'Lebanon': 'Lebanon',
    'Lesotho': 'Lesotho',
    'Liberia': 'Liberia',
    'Lithuania': 'Lithuania',
    'Luxembourg': 'Luxembourg',
    'Madagascar': 'Madagascar',
    'Malawi': 'Malawi',
    'Malaysia': 'Malaysia',
    'Mali': 'Mali',
    'Mauritania': 'Mauritania',
    'Mexico': 'Mexico',
    'Mongolia': 'Mongolia',
    'Montenegro': 'Montenegro',
    'Morocco': 'Morocco',
    'Mozambique': 'Mozambique',
    'Myanmar': 'Myanmar',
    'Namibia': 'Namibia',
    'Nepal': 'Nepal',
    'Netherlands': 'Netherlands',
    'New Zealand': 'New Zealand',
    'New caledonia': 'New Caledonia',
    'Nicaragua': 'Nicaragua',
    'Niger': 'Niger',
    'Norway': 'Norway',
    'Oman': 'Oman',
    'Pakistan': 'Pakistan',
    'Papua New Guinea': 'Papua New Guinea',
    'Paraguay': 'Paraguay',
    'Peru': 'Peru',
    'Philippines': 'Philippines',
    'Poland': 'Poland',
    'Portugal': 'Portugal',
    'Qatar': 'Qatar',
    'Romania': 'Romania',
    'Rwanda': 'Rwanda',
    'Saudi Arabia': 'Saudi Arabia',
    'Senegal': 'Senegal',
    'Serbia': 'Serbia',
    'Sierra Leone': 'Sierra Leone',
    'Slovakia': 'Slovakia',
    'Slovenia': 'Slovenia',
    'Somalia': 'Somalia',
    'South africa': 'South Africa',
    'Spain': 'Spain',
    'Sri Lanka': 'Sri Lanka',
    'Sudan': 'Sudan',
    'Suriname': 'Suriname',
    'Sweden': 'Sweden',
    'Switzerland': 'Switzerland',
    'Tajikistan': 'Tajikistan',
    'Thailand': 'Thailand',
    'Togo': 'Togo',
    'Trinidad and Tobago': 'Trinidad and Tobago',
    'Tunisia': 'Tunisia',
    'Turkey': 'Turkey',
    'Turkmenistan': 'Turkmenistan',
    'Uganda': 'Uganda',
    'Ukraine': 'Ukraine',
    'United Kingdom': 'United Kingdom',
    'United States of America': 'United States of America',
    'United arab emirates': 'United Arab Emirates',
    'Uruguay': 'Uruguay',
    'Uzbekistan': 'Uzbekistan',
    'Yemen': 'Yemen',
    'Zambia': 'Zambia',
    'Zimbabwe': 'Zimbabwe'
}
